aliases: []
creation_timestamp: 1768064330228
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1768064330228
metrics: null
model_id: m-cdf1ac1408e24a6b8138783eba54c554
name: taxi-pred
params: null
run_id: ''
run_link: ''
source: mlflow-artifacts:/572565819945319502/models/m-cdf1ac1408e24a6b8138783eba54c554/artifacts
status: READY
status_message: null
storage_location: mlflow-artifacts:/572565819945319502/models/m-cdf1ac1408e24a6b8138783eba54c554/artifacts
user_id: null
version: 1
